#!/usr/bin/env python
"""
Display Visual Log Tool

This script provides a better way to view the visual logs generated by AI scenario tests.
It adds color, formatting, and improved readability to the log output.
"""

import os
import sys
import argparse
import re
from datetime import datetime
from typing import List, Optional, Dict, Any

# ANSI color codes for terminal output
COLORS = {
    'RESET': '\033[0m',
    'BOLD': '\033[1m',
    'RED': '\033[91m',
    'GREEN': '\033[92m',
    'YELLOW': '\033[93m',
    'BLUE': '\033[94m',
    'MAGENTA': '\033[95m',
    'CYAN': '\033[96m',
    'WHITE': '\033[97m',
    'BG_RED': '\033[41m',
    'BG_GREEN': '\033[42m',
    'BG_YELLOW': '\033[43m',
    'BG_BLUE': '\033[44m',
    'BG_MAGENTA': '\033[45m',
    'BG_CYAN': '\033[46m',
}

# Terrain type colors
TERRAIN_COLORS = {
    'P': COLORS['GREEN'],      # Plains
    'M': COLORS['YELLOW'],     # Mountains
    'F': COLORS['BG_GREEN'],   # Forest
    'R': COLORS['BLUE'],       # River
    'B': COLORS['CYAN'],       # Bridge
    'V': COLORS['MAGENTA'],    # Village
    'C': COLORS['YELLOW'],     # Castle
    'T': COLORS['YELLOW'],     # Throne
    'W': COLORS['BLUE'],       # Water
    'S': COLORS['YELLOW'],     # Sand
}

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description='Display a visual log with improved formatting')
    parser.add_argument('log_file', help='Path to the visual log file to display')
    parser.add_argument('--no-color', action='store_true', help='Disable colored output')
    parser.add_argument('--summary', action='store_true', help='Show only turn summaries, not full maps')
    return parser.parse_args()

def read_log_file(file_path: str) -> List[str]:
    """Read the log file contents."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return file.readlines()
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(1)

def format_map(map_text: str, use_color: bool = True) -> str:
    """Format a map section with appropriate colors."""
    if not use_color:
        return map_text
    
    formatted_text = ""
    for line in map_text.split('\n'):
        formatted_line = ""
        for char in line:
            if char in TERRAIN_COLORS:
                formatted_line += f"{TERRAIN_COLORS[char]}{char}{COLORS['RESET']}"
            elif char.isalpha() and char.isupper():  # Unit indicators
                formatted_line += f"{COLORS['BG_RED']}{char}{COLORS['RESET']}" if char == 'E' else f"{COLORS['BG_BLUE']}{char}{COLORS['RESET']}"
            else:
                formatted_line += char
        formatted_text += formatted_line + "\n"
    return formatted_text

def format_action(action_text: str, use_color: bool = True) -> str:
    """Format an action line with appropriate colors."""
    if not use_color:
        return action_text
    
    # Highlight unit names and action types
    unit_pattern = r"(\w+) \(([A-Z_]+)\)"
    action_pattern = r"performs ([A-Z_]+)"
    
    formatted_text = action_text
    formatted_text = re.sub(unit_pattern, f"{COLORS['BOLD']}\\1{COLORS['RESET']} ({COLORS['CYAN']}\\2{COLORS['RESET']})", formatted_text)
    formatted_text = re.sub(action_pattern, f"performs {COLORS['YELLOW']}\\1{COLORS['RESET']}", formatted_text)
    
    return formatted_text

def format_section_header(header: str, use_color: bool = True) -> str:
    """Format a section header with appropriate colors."""
    if not use_color:
        return header
    
    if "INITIAL STATE" in header:
        return f"{COLORS['BG_BLUE']}{COLORS['WHITE']}{header}{COLORS['RESET']}"
    elif "TURN" in header:
        turn_num = re.search(r"TURN (\d+)", header)
        if turn_num:
            turn_str = f"TURN {turn_num.group(1)}"
            return header.replace(turn_str, f"{COLORS['BG_YELLOW']}{COLORS['BOLD']}{turn_str}{COLORS['RESET']}")
    elif "PHASE" in header:
        phase_name = header.strip()
        return f"{COLORS['MAGENTA']}{COLORS['BOLD']}{phase_name}{COLORS['RESET']}"
    
    return f"{COLORS['BOLD']}{header}{COLORS['RESET']}"

def display_log(content: List[str], use_color: bool = True, summary_only: bool = False) -> None:
    """Display the log content with improved formatting."""
    in_map_section = False
    map_text = ""
    
    for line in content:
        line = line.rstrip()
        
        # Skip empty lines outside of map sections
        if not line and not in_map_section:
            print()
            continue
        
        # Handle section headers
        if line.startswith('=====') or line.startswith('-----') or line.startswith('---'):
            if in_map_section:
                if not summary_only:
                    print(format_map(map_text, use_color))
                in_map_section = False
                map_text = ""
            
            print(format_section_header(line, use_color))
            
            if "STATE" in line or "TURN" in line:
                in_map_section = True
            
        # Handle actions
        elif line.strip().startswith('- '):
            print(format_action(line, use_color))
        # Handle action results
        elif line.strip().startswith('-> '):
            print(f"  {COLORS['GREEN'] if use_color else ''}{line.strip()}{COLORS['RESET'] if use_color else ''}")
        # Collect map text
        elif in_map_section:
            map_text += line + "\n"
        # Print other lines normally
        else:
            print(line)
    
    # Print any remaining map text
    if in_map_section and map_text and not summary_only:
        print(format_map(map_text, use_color))

def main() -> None:
    """Main function to run the display tool."""
    args = parse_args()
    content = read_log_file(args.log_file)
    
    # Print header with file information
    file_stats = os.stat(args.log_file)
    created_time = datetime.fromtimestamp(file_stats.st_ctime)
    
    print(f"\n{COLORS['BOLD'] if not args.no_color else ''}=== Visual Log: {os.path.basename(args.log_file)} ==={COLORS['RESET'] if not args.no_color else ''}")
    print(f"Created: {created_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Size: {file_stats.st_size} bytes")
    print(f"{'Summary mode' if args.summary else 'Full display mode'}\n")
    
    display_log(content, not args.no_color, args.summary)

if __name__ == "__main__":
    main() 